services:
  - type: web
    name: nss-app
    runtime: php
    plan: free
    region: singapore
    branch: main
    buildCommand: bash build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://nss-app.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STACK
        value: single
      - key: PHP_VERSION
        value: 8.3
      - key: BCRYPT_ROUNDS
        value: 10
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: APP_MAINTENANCE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: BROADCAST_CONNECTION
        value: log
      - key: MAIL_MAILER
        value: log
      - key: VITE_APP_NAME
        value: "${APP_NAME}"
